# Generated by Django 2.0 on 2023-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_xiangqing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xingming', models.CharField(max_length=64, verbose_name='姓名')),
                ('hezuo_guimo', models.CharField(max_length=64, verbose_name='初始规模')),
                ('shangmiao_count', models.IntegerField(verbose_name='上苗数量')),
                ('lilun_count', models.IntegerField(verbose_name='理论提货量')),
                ('hezuo_date', models.DateTimeField(verbose_name='合作日期')),
                ('shangmiao_date', models.DateTimeField(verbose_name='上苗日期')),
                ('maimiao_date', models.DateTimeField(verbose_name='卖苗日期')),
                ('shiji_count', models.IntegerField(verbose_name='理论提货量')),
                ('chuangjian_date', models.DateTimeField(verbose_name='提货日期')),
            ],
        ),
        migrations.CreateModel(
            name='CustomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=64, verbose_name='手机号')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('mate', models.CharField(max_length=32, verbose_name='配偶')),
                ('custom', models.CharField(max_length=32, verbose_name='客户')),
                ('scale', models.CharField(max_length=64, verbose_name='规模')),
                ('property', models.CharField(max_length=64, verbose_name='资产')),
                ('debt', models.CharField(max_length=64, verbose_name='负债')),
                ('BreedingAddress', models.CharField(max_length=128, verbose_name='养殖地址')),
                ('account', models.CharField(max_length=64, verbose_name='银行账户')),
                ('type', models.CharField(max_length=32, verbose_name='客户类型')),
                ('area', models.CharField(max_length=32, verbose_name='所在区域')),
                ('credit', models.IntegerField(verbose_name='授信额度')),
                ('credit_date', models.DateTimeField(verbose_name='授信日期')),
                ('use_credit', models.IntegerField(verbose_name='使用额度')),
            ],
        ),
        migrations.CreateModel(
            name='Tihuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_use', models.IntegerField(verbose_name='今日支用')),
                ('today_siliao', models.IntegerField(verbose_name='今日提货量')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
