# Generated by Django 2.0 on 2023-09-13 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 16, 14, 11, 2475), verbose_name='提货日期'),
        ),
    ]
