# Generated by Django 2.0 on 2023-09-13 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tihuo_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_xiangqing',
            name='chuangjian_date',
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 13, 16, 34, 57, 341065), verbose_name='提货日期'),
        ),
    ]
