# Generated by Django 2.0 on 2023-09-22 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230913_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 19, 11, 32, 255365), verbose_name='提货日期'),
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today_siliao',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='今日提货量'),
        ),
    ]
