# Generated by Django 2.0 on 2023-09-22 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230922_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 19, 16, 51, 896530), verbose_name='提货日期'),
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today_siliao',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='今日提货量'),
        ),
    ]
