# Generated by Django 2.0 on 2023-09-29 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230922_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 15, 5, 51, 506199), verbose_name='提货日期'),
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today_siliao',
            field=models.FloatField(verbose_name='今日提货量'),
        ),
    ]
