# Generated by Django 2.0 on 2023-10-01 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230929_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_xiangqing',
            name='hezuo_moshi',
            field=models.CharField(default='保底合同', max_length=64, verbose_name='合作模式'),
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 13, 57, 57, 303272), verbose_name='提货日期'),
        ),
    ]
