# Generated by Django 2.0 on 2023-10-01 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20231001_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominfo',
            name='lirun',
            field=models.IntegerField(default='0', verbose_name='利润'),
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 16, 39, 7, 101944), verbose_name='提货日期'),
        ),
    ]
