# Generated by Django 2.0 on 2023-10-02 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20231001_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tihuo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 15, 56, 44, 384492), verbose_name='提货日期'),
        ),
    ]
