# Generated by Django 2.0 on 2023-10-02 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20231002_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 16, 0, 46, 205344), verbose_name='提货日期'),
        ),
    ]
