# Generated by Django 2.0 on 2023-10-02 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20231002_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tihuo',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 16, 2, 48, 190239), verbose_name='提货日期'),
        ),
    ]
